# Generated by Django 3.2.3 on 2021-05-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstudylog',
            name='study_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentstudylog',
            name='sum_study_time',
            field=models.IntegerField(default=0),
        ),
    ]
