# Generated by Django 3.2.3 on 2021-06-23 15:58

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210527_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('username', models.CharField(default='こすこす', max_length=200)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='ThisWeekStudyTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('username', models.CharField(default='こすこす', max_length=200)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('weekly_study_time', models.BigIntegerField(default=0)),
                ('week_name', models.CharField(default='2021/5/31~2021/6/7', max_length=200)),
            ],
        ),
    ]
