# Generated by Django 3.2.3 on 2021-07-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentvideo_thisweekstudytime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='studentvideo',
            name='videoPath',
            field=models.TextField(default='default'),
        ),
    ]
