# Generated by Django 3.2.3 on 2021-08-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210707_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstudylog',
            name='weekly_goal',
        ),
        migrations.AddField(
            model_name='studentstudylog',
            name='goal_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentstudylog',
            name='goal_start',
            field=models.IntegerField(default=0),
        ),
    ]
