# Generated by Django 3.2.3 on 2021-08-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210816_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstudylog',
            name='goal_end',
            field=models.CharField(default='0000/00/00', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentstudylog',
            name='goal_start',
            field=models.CharField(default='0000/00/00', max_length=200),
        ),
    ]
